In [7]:
import pandas as pd

In [8]:
fao_statistics = pd.read_csv("../export/final_data_2020.csv", index_col="pays")
fao_statistics

,code_groupe_de_pays,groupe_de_pays,country_code,population_totale,besoins_energetiques_alimentaires_moyens_(kcal/personne/jour),densite_du_reseau_ferroviaire_(pour_100_km_carres_de_surface_totale_du_pays),"pib_par_habitant,_($_ppa_internationaux_constants_de_2017)",stabilite_politique_et_absence_de_violence/terrorisme_(indice),taux_de_dependance_a_l'egard_des_importations_cerealieres_(%)_(moyenne_sur_3_ans),valeur_des_importations_alimentaires_par_rapport_aux_exportations_totales_de_marchandises_(%)_(moyenne_sur_3_ans),...,valeur_des_importations_-_quantite_periode_de_reference,indicateur_emploi,production_brute_2014-2016_(millier_int$),reserves,disponibilite_interieure,exportations_-_quantite,importations_-_quantite,nourriture,production,variation_de_stock
pays,,,,,,,,,,,,,,,,,,,,,
Côte d'Ivoire,5100,Afrique,107,28915449.0,2233.0,0.2,6.161200e+09,-1.03,48.4,12.0,...,1432922.0,NaN,142705.0,89511.0,72.0,0.0,1.0,72.0,71.0,0.0
Kenya,5100,Afrique,114,52217334.0,2254.0,0.0,5.079900e+09,-1.01,47.8,42.0,...,2044179.0,NaN,132879.0,57178.0,69.0,0.0,1.0,69.0,69.0,1.0
Lesotho,5100,Afrique,122,2235727.0,2299.0,0.0,2.440900e+09,-0.25,100.0,30.0,...,282993.0,NaN,2.0,471.0,4.0,NaN,3.0,4.0,1.0,0.0
Libéria,5100,Afrique,123,5149463.0,2213.0,0.0,1.513800e+09,-0.31,71.8,60.0,...,309123.0,NaN,26665.0,8031.0,56.0,0.0,42.0,56.0,15.0,0.0
Libye,5100,Afrique,124,7045399.0,2384.0,0.0,1.166060e+10,-2.46,92.5,16.0,...,2956348.0,NaN,249303.0,36550.0,223.0,NaN,96.0,223.0,127.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Îles Wallis-et-Futuna,5000,Monde,243,11616.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Samoa,5000,Monde,244,211944.0,2335.0,0.0,6.689700e+09,1.15,0.0,218.0,...,82663.0,NaN,625.0,386.0,16.0,NaN,16.0,16.0,0.0,0.0
Îles Cook,5000,Monde,47,15643.0,0.0,0.0,0.000000e+00,0.00,0.0,176.0,...,27954.0,NaN,80.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN
Samoa américaines,5000,Monde,5,49761.0,0.0,0.0,0.000000e+00,1.09,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Polynésie française,5000,Monde,70,279209.0,2440.0,0.0,0.000000e+00,0.00,0.0,326.0,...,363838.0,NaN,1100.0,325.0,17.0,NaN,17.0,14.0,1.0,1.0

In [9]:
fao_statistics.columns

Index(['code_groupe_de_pays', 'groupe_de_pays', 'country_code',
       'population_totale',
       'besoins_energetiques_alimentaires_moyens_(kcal/personne/jour)',
       'densite_du_reseau_ferroviaire_(pour_100_km_carres_de_surface_totale_du_pays)',
       'pib_par_habitant,_($_ppa_internationaux_constants_de_2017)',
       'stabilite_politique_et_absence_de_violence/terrorisme_(indice)',
       'taux_de_dependance_a_l'egard_des_importations_cerealieres_(%)_(moyenne_sur_3_ans)',
       'valeur_des_importations_alimentaires_par_rapport_aux_exportations_totales_de_marchandises_(%)_(moyenne_sur_3_ans)',
       'variabilite_des_disponibilites_alimentaires_par_habitant_(kcal/personne/jour)',
       'valeur_des_exportations_-_prix_periode_de_reference',
       'valeur_des_exportations_-_quantite_periode_de_reference',
       'valeur_des_importations_-_prix_periode_de_reference',
       'valeur_des_importations_-_quantite_periode_de_reference',
       'indicateur_emploi', 'production_brute_2014-2016_(millier_int$)',
       'reserves', 'disponibilite_interieure', 'exportations_-_quantite',
       'importations_-_quantite', 'nourriture', 'production',
       'variation_de_stock'],
      dtype='object')

fao_statistics = fao_statistics.drop(columns=['code_groupe_de_pays', 'groupe_de_pays', 'code_groupe_m49', 'code_pays',
'code_m49', 'code_iso2', 'code_iso3', 'country_code', 'zone', 'zone_secu',
'zone_indices', 'femmes', 'hommes', 'population_rurale', 'population_urbaine'])

In [10]:
fao_statistics

,code_groupe_de_pays,groupe_de_pays,country_code,population_totale,besoins_energetiques_alimentaires_moyens_(kcal/personne/jour),densite_du_reseau_ferroviaire_(pour_100_km_carres_de_surface_totale_du_pays),"pib_par_habitant,_($_ppa_internationaux_constants_de_2017)",stabilite_politique_et_absence_de_violence/terrorisme_(indice),taux_de_dependance_a_l'egard_des_importations_cerealieres_(%)_(moyenne_sur_3_ans),valeur_des_importations_alimentaires_par_rapport_aux_exportations_totales_de_marchandises_(%)_(moyenne_sur_3_ans),...,valeur_des_importations_-_quantite_periode_de_reference,indicateur_emploi,production_brute_2014-2016_(millier_int$),reserves,disponibilite_interieure,exportations_-_quantite,importations_-_quantite,nourriture,production,variation_de_stock
pays,,,,,,,,,,,,,,,,,,,,,
Côte d'Ivoire,5100,Afrique,107,28915449.0,2233.0,0.2,6.161200e+09,-1.03,48.4,12.0,...,1432922.0,NaN,142705.0,89511.0,72.0,0.0,1.0,72.0,71.0,0.0
Kenya,5100,Afrique,114,52217334.0,2254.0,0.0,5.079900e+09,-1.01,47.8,42.0,...,2044179.0,NaN,132879.0,57178.0,69.0,0.0,1.0,69.0,69.0,1.0
Lesotho,5100,Afrique,122,2235727.0,2299.0,0.0,2.440900e+09,-0.25,100.0,30.0,...,282993.0,NaN,2.0,471.0,4.0,NaN,3.0,4.0,1.0,0.0
Libéria,5100,Afrique,123,5149463.0,2213.0,0.0,1.513800e+09,-0.31,71.8,60.0,...,309123.0,NaN,26665.0,8031.0,56.0,0.0,42.0,56.0,15.0,0.0
Libye,5100,Afrique,124,7045399.0,2384.0,0.0,1.166060e+10,-2.46,92.5,16.0,...,2956348.0,NaN,249303.0,36550.0,223.0,NaN,96.0,223.0,127.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Îles Wallis-et-Futuna,5000,Monde,243,11616.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Samoa,5000,Monde,244,211944.0,2335.0,0.0,6.689700e+09,1.15,0.0,218.0,...,82663.0,NaN,625.0,386.0,16.0,NaN,16.0,16.0,0.0,0.0
Îles Cook,5000,Monde,47,15643.0,0.0,0.0,0.000000e+00,0.00,0.0,176.0,...,27954.0,NaN,80.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN
Samoa américaines,5000,Monde,5,49761.0,0.0,0.0,0.000000e+00,1.09,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Polynésie française,5000,Monde,70,279209.0,2440.0,0.0,0.000000e+00,0.00,0.0,326.0,...,363838.0,NaN,1100.0,325.0,17.0,NaN,17.0,14.0,1.0,1.0