In [1]:
import pandas as pd
from unidecode import unidecode

In [2]:
valeur_prod_agricole = pd.read_csv('../database/valeur_production_agricole_2020.csv', dtype=str)
valeur_prod_agricole = valeur_prod_agricole[
    (valeur_prod_agricole['Code Produit (FAO)'] == '1094') &
    (valeur_prod_agricole['Code Élément'] == '152')
]
valeur_prod_agricole

,Code Domaine,Domaine,Code zone (FAO),Zone,Code Élément,Élément,Code Produit (FAO),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
69,QV,Valeur de la Production Agricole,2,Afghanistan,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,2,E,Valeur estimée
382,QV,Valeur de la Production Agricole,202,Afrique du Sud,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,3625698,E,Valeur estimée
694,QV,Valeur de la Production Agricole,3,Albanie,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,22103,E,Valeur estimée
951,QV,Valeur de la Production Agricole,4,Algérie,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,927230,E,Valeur estimée
1309,QV,Valeur de la Production Agricole,7,Angola,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,97280,E,Valeur estimée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33368,QV,Valeur de la Production Agricole,155,Vanuatu,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,1113,E,Valeur estimée
33574,QV,Valeur de la Production Agricole,237,Viet Nam,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,2180312,E,Valeur estimée
33848,QV,Valeur de la Production Agricole,249,Yémen,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,370781,E,Valeur estimée
33975,QV,Valeur de la Production Agricole,251,Zambie,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,95445,E,Valeur estimée
34155,QV,Valeur de la Production Agricole,181,Zimbabwe,152,Production Brute 2014-2016 (millier Int$),1094,"Viande indigène, poulet, fraîche ou réfrigérée",2020,2020,1000 Int$,214228,E,Valeur estimée

In [3]:
def preprocess_valeur_prod_agricole_data(valeur_prod_agricole):
    valeur_prod_agricole = valeur_prod_agricole.drop(columns=['Description du Symbole', 'Symbole', 'Code année', 'Année', 'Produit', 'Code Produit (FAO)', 'Domaine', 'Code Élément', 'Code Domaine', 'Unité'])
    return valeur_prod_agricole
valeur_prod_agricole = preprocess_valeur_prod_agricole_data(valeur_prod_agricole)
valeur_prod_agricole

,Code zone (FAO),Zone,Élément,Valeur
69,2,Afghanistan,Production Brute 2014-2016 (millier Int$),2
382,202,Afrique du Sud,Production Brute 2014-2016 (millier Int$),3625698
694,3,Albanie,Production Brute 2014-2016 (millier Int$),22103
951,4,Algérie,Production Brute 2014-2016 (millier Int$),927230
1309,7,Angola,Production Brute 2014-2016 (millier Int$),97280
...,...,...,...,...
33368,155,Vanuatu,Production Brute 2014-2016 (millier Int$),1113
33574,237,Viet Nam,Production Brute 2014-2016 (millier Int$),2180312
33848,249,Yémen,Production Brute 2014-2016 (millier Int$),370781
33975,251,Zambie,Production Brute 2014-2016 (millier Int$),95445
34155,181,Zimbabwe,Production Brute 2014-2016 (millier Int$),214228

In [4]:
def convert_valeur_prod_agricole_to_numeric(valeur_prod_agricole):
    valeur_prod_agricole['Valeur'] = valeur_prod_agricole['Valeur'].astype(float)
    return valeur_prod_agricole

valeur_prod_agricole_transformed = convert_valeur_prod_agricole_to_numeric(valeur_prod_agricole)
valeur_prod_agricole_transformed

,Code zone (FAO),Zone,Élément,Valeur
69,2,Afghanistan,Production Brute 2014-2016 (millier Int$),2.0
382,202,Afrique du Sud,Production Brute 2014-2016 (millier Int$),3625698.0
694,3,Albanie,Production Brute 2014-2016 (millier Int$),22103.0
951,4,Algérie,Production Brute 2014-2016 (millier Int$),927230.0
1309,7,Angola,Production Brute 2014-2016 (millier Int$),97280.0
...,...,...,...,...
33368,155,Vanuatu,Production Brute 2014-2016 (millier Int$),1113.0
33574,237,Viet Nam,Production Brute 2014-2016 (millier Int$),2180312.0
33848,249,Yémen,Production Brute 2014-2016 (millier Int$),370781.0
33975,251,Zambie,Production Brute 2014-2016 (millier Int$),95445.0
34155,181,Zimbabwe,Production Brute 2014-2016 (millier Int$),214228.0

In [5]:
def transform_valeur_prod_agricole_data(valeur_prod_agricole):
    grouper_lignes = valeur_prod_agricole.groupby(['Code zone (FAO)', 'Zone', 'Élément'], as_index=False).sum()
    return grouper_lignes
grouper_lignes = transform_valeur_prod_agricole_data(valeur_prod_agricole_transformed)
grouper_lignes

,Code zone (FAO),Zone,Élément,Valeur
0,1,Arménie,Production Brute 2014-2016 (millier Int$),22694.0
1,10,Australie,Production Brute 2014-2016 (millier Int$),2441665.0
2,100,Inde,Production Brute 2014-2016 (millier Int$),8593866.0
3,101,Indonésie,Production Brute 2014-2016 (millier Int$),6988395.0
4,102,Iran (République islamique d'),Production Brute 2014-2016 (millier Int$),4669888.0
...,...,...,...,...
163,91,Guyana,Production Brute 2014-2016 (millier Int$),81916.0
164,93,Haïti,Production Brute 2014-2016 (millier Int$),14813.0
165,95,Honduras,Production Brute 2014-2016 (millier Int$),359543.0
166,96,Chine - RAS de Hong-Kong,Production Brute 2014-2016 (millier Int$),34299.0
167,99,Islande,Production Brute 2014-2016 (millier Int$),17427.0

In [6]:
def transform_valeur_prod_agricole_data(grouper_lignes):
    valeur_prod_agricole = grouper_lignes.pivot(index=['Code zone (FAO)','Zone'], columns='Élément', values='Valeur')
    valeur_prod_agricole = valeur_prod_agricole.reset_index()
    valeur_prod_agricole = valeur_prod_agricole.rename(columns={'Code zone (FAO)': 'country_code'})
    return valeur_prod_agricole

valeur_prod_agricole_transformed = transform_valeur_prod_agricole_data(grouper_lignes)
valeur_prod_agricole_transformed

Élément,country_code,Zone,Production Brute 2014-2016 (millier Int$)
0,1,Arménie,22694.0
1,10,Australie,2441665.0
2,100,Inde,8593866.0
3,101,Indonésie,6988395.0
4,102,Iran (République islamique d'),4669888.0
...,...,...,...
163,91,Guyana,81916.0
164,93,Haïti,14813.0
165,95,Honduras,359543.0
166,96,Chine - RAS de Hong-Kong,34299.0
167,99,Islande,17427.0

In [7]:
def transform_regex_valeur_prod_agricole(valeur_prod_agricole_transformed):
    valeur_prod_agricole_transformed.columns = valeur_prod_agricole_transformed.columns.str.replace(' ', '_', regex=False)
    valeur_prod_agricole_transformed.columns = valeur_prod_agricole_transformed.columns.str.lower()
    valeur_prod_agricole_transformed.columns = [unidecode(col) for col in valeur_prod_agricole_transformed.columns]
    return valeur_prod_agricole_transformed

valeur_prod_agricole_transformed = transform_regex_valeur_prod_agricole(valeur_prod_agricole_transformed)

In [8]:
def save_transformed_valeur_prod_agricole_data(valeur_prod_agricole_transformed):
    valeur_prod_agricole_transformed.to_csv('../export/valeur_prod_agricole_2020.csv', index=False, encoding='utf-8')
    print("Valeur production agricole data transformed and saved successfully.")

save_transformed_valeur_prod_agricole_data(valeur_prod_agricole_transformed)

Valeur production agricole data transformed and saved successfully.