In [4]:
import pandas as pd
from unidecode import unidecode

In [5]:
indicateur_emploi = pd.read_csv('../database/indicateur_emploi_production_animal_2020.csv', dtype=str)
indicateur_emploi

,Code Domaine,Domaine,Code zone (FAO),Zone,Code indicateur,Indicateur,Code sexe,Sexe,Code année,Année,Code Élément,Élément,Code source,Source,Unité,Valeur,Symbole,Description du Symbole,Note
0,OEA,Indicateurs de l’emploi: Agriculture et systèm...,202,Afrique du Sud,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3023,Labour force survey,1000 No,3778.67,X,Chiffre de sources internationales,Repository: ILO-STATISTICS - Micro data proces...
1,OEA,Indicateurs de l’emploi: Agriculture et systèm...,79,Allemagne,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3023,Labour force survey,1000 No,453.21,X,Chiffre de sources internationales,Break in series: Methodology revised | Remarks...
2,OEA,Indicateurs de l’emploi: Agriculture et systèm...,9,Argentine,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3023,Labour force survey,1000 No,44.89,X,Chiffre de sources internationales,Repository: ILO-STATISTICS - Micro data proces...
3,OEA,Indicateurs de l’emploi: Agriculture et systèm...,1,Arménie,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3021,Household income and expenditure survey,1000 No,361.06,X,Chiffre de sources internationales,Repository: ILO-STATISTICS - Micro data proces...
4,OEA,Indicateurs de l’emploi: Agriculture et systèm...,10,Australie,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3021,Household income and expenditure survey,1000 No,314.85,X,Chiffre de sources internationales,Repository: ILO-STATISTICS - Micro data proces...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,OEA,Indicateurs de l’emploi: Agriculture et systèm...,230,Ukraine,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3023,Labour force survey,1000 No,2148.19,X,Chiffre de sources internationales,Repository: ILO-STATISTICS - Micro data proces...
81,OEA,Indicateurs de l’emploi: Agriculture et systèm...,234,Uruguay,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3023,Labour force survey,1000 No,110.89,X,Chiffre de sources internationales,Break in series: Methodology revised Repositor...
82,OEA,Indicateurs de l’emploi: Agriculture et systèm...,155,Vanuatu,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3035,Population census,1000 No,30.84,X,Chiffre de sources internationales,Repository: ILO-STATISTICS - Micro data proces...
83,OEA,Indicateurs de l’emploi: Agriculture et systèm...,237,Viet Nam,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3023,Labour force survey,1000 No,15353.17,X,Chiffre de sources internationales,Repository: ILO-STATISTICS - Micro data proces...
84,OEA,Indicateurs de l’emploi: Agriculture et systèm...,251,Zambie,21111,"Employment in crop and animal production, hunt...",1,Total,2020,2020,6199,Valeur,3023,Labour force survey,1000 No,3291.84,X,Chiffre de sources internationales,Repository: ILO-STATISTICS - Micro data proces...

In [9]:
indicateur_emploi = pd.read_csv('../database/indicateur_emploi_production_animal_2020.csv', dtype=str)
def preprocess_indicateur_emploi_data(indicateur_emploi):
    indicateur_emploi = indicateur_emploi.drop(columns=['Note', 'Description du Symbole', 'Symbole', 'Code année', 'Source', 'Code source', 'Domaine', 'Code Domaine', 'Unité', 'Code indicateur', 'Indicateur', 'Code Élément', 'Code sexe', 'Sexe'])
    return indicateur_emploi
indicateur_emploi = preprocess_indicateur_emploi_data(indicateur_emploi)
indicateur_emploi

   Code zone (FAO)            Zone Année Élément    Valeur
0              202  Afrique du Sud  2020  Valeur   3778.67
1               79       Allemagne  2020  Valeur    453.21
2                9       Argentine  2020  Valeur     44.89
3                1         Arménie  2020  Valeur    361.06
4               10       Australie  2020  Valeur    314.85
..             ...             ...   ...     ...       ...
80             230         Ukraine  2020  Valeur   2148.19
81             234         Uruguay  2020  Valeur    110.89
82             155         Vanuatu  2020  Valeur     30.84
83             237        Viet Nam  2020  Valeur  15353.17
84             251          Zambie  2020  Valeur   3291.84

[85 rows x 5 columns]

In [10]:
def convert_indicateur_emploi_to_numeric(indicateur_emploi):
    indicateur_emploi['Valeur'] = indicateur_emploi['Valeur'].astype(float)
    return indicateur_emploi

indicateur_emploi_transformed = convert_indicateur_emploi_to_numeric(indicateur_emploi)
indicateur_emploi_transformed

   Code zone (FAO)            Zone Année Élément    Valeur
0              202  Afrique du Sud  2020  Valeur   3778.67
1               79       Allemagne  2020  Valeur    453.21
2                9       Argentine  2020  Valeur     44.89
3                1         Arménie  2020  Valeur    361.06
4               10       Australie  2020  Valeur    314.85
..             ...             ...   ...     ...       ...
80             230         Ukraine  2020  Valeur   2148.19
81             234         Uruguay  2020  Valeur    110.89
82             155         Vanuatu  2020  Valeur     30.84
83             237        Viet Nam  2020  Valeur  15353.17
84             251          Zambie  2020  Valeur   3291.84

[85 rows x 5 columns]

In [11]:
def transform_indicateur_emploi_data(indicateur_emploi):
    grouper_lignes = indicateur_emploi.groupby(['Code zone (FAO)', 'Zone', 'Élément'], as_index=False).sum()
    return grouper_lignes
grouper_lignes = transform_indicateur_emploi_data(indicateur_emploi_transformed)
grouper_lignes

   Code zone (FAO)                            Zone Élément Année     Valeur
0                1                         Arménie  Valeur  2020     361.06
1               10                       Australie  Valeur  2020     314.85
2              100                            Inde  Valeur  2020  171201.84
3              102  Iran (République islamique d')  Valeur  2020    3751.40
4              104                         Irlande  Valeur  2020      96.47
..             ...                             ...     ...   ...        ...
80               9                       Argentine  Valeur  2020      44.89
81              95                        Honduras  Valeur  2020     813.30
82              97                         Hongrie  Valeur  2020     191.54
83              98                         Croatie  Valeur  2020      90.35
84              99                         Islande  Valeur  2020       3.64

[85 rows x 5 columns]

In [12]:
def transform_indicateur_emploi_data(grouper_lignes):
    indicateur_emploi = grouper_lignes.pivot(index=['Code zone (FAO)','Zone'], columns='Élément', values='Valeur')
    indicateur_emploi = indicateur_emploi.reset_index()
    indicateur_emploi = indicateur_emploi.rename(columns={'Code zone (FAO)': 'country_code'})
    return indicateur_emploi

indicateur_emploi_transformed = transform_indicateur_emploi_data(grouper_lignes)
indicateur_emploi_transformed

Élément country_code                            Zone     Valeur
0                  1                         Arménie     361.06
1                 10                       Australie     314.85
2                100                            Inde  171201.84
3                102  Iran (République islamique d')    3751.40
4                104                         Irlande      96.47
..               ...                             ...        ...
80                 9                       Argentine      44.89
81                95                        Honduras     813.30
82                97                         Hongrie     191.54
83                98                         Croatie      90.35
84                99                         Islande       3.64

[85 rows x 3 columns]

In [13]:
def transform_regex_indicateur_emploi(indicateur_emploi_transformed):
    indicateur_emploi_transformed.columns = indicateur_emploi_transformed.columns.str.replace(' ', '_', regex=False)
    indicateur_emploi_transformed.columns = indicateur_emploi_transformed.columns.str.lower()
    indicateur_emploi_transformed.columns = [unidecode(col) for col in indicateur_emploi_transformed.columns]
    return indicateur_emploi_transformed

indicateur_emploi_transformed = transform_regex_indicateur_emploi(indicateur_emploi_transformed)

In [14]:
def save_transformed_indicateur_emploi_data(indicateur_emploi_transformed):
    indicateur_emploi_transformed.to_csv('../export/indicateur_emploi_2020.csv', index=False, encoding='utf-8')
    print("Indicateur emploi data transformed and saved successfully.")

save_transformed_indicateur_emploi_data(indicateur_emploi_transformed)

Indicateur emploi data transformed and saved successfully.